# pragma once

# define	TIMEOUT_SECONDS	60

# define	MAX_HEADER		100
# define	MAX_URI_LENGTH	4096
# define	MAX_LINE_LENGTH	8192
# define	MAX_BODY_SIZE	(2ULL * 1024 * 1024 * 1024)

# define	CRLF			"\r\n"
# define	END_HEADER		"\r\n\r\n"
# define	HTTP_VERSION	"HTTP/1.1"

enum BodyType
{
	RAW,
	JSON,
	MULTIPART,
	URL_ENCODED
};

enum RequestState
{
	BEGIN,
	LINE,
	HEADERS,
	BODY,
	COMPLETE,
	ERROR
};

enum BodyState
{
	BS_START,
	BS_CHUNK_SIZE,
	BS_CHUNK_DATA,
	BS_CHUNK_END,
	BS_TRAILERS,
	BS_COMPLETE
};

enum HttpStatusCode
{
	START,
	OK = 200,
	BAD_REQUEST = 400,
	METHOD_NOT_ALLOWED = 405,
	REQUEST_TIMEOUT = 408,
	LENGTH_REQUIRED = 411,
	PAYLOAD_TOO_LARGE = 413,
	URI_TOO_LONG = 414,
	UNSUPPORTED_MEDIA_TYPE = 415,
	HEADER_FIELDS_TOO_LARGE = 431,
	INTERNAL_SERVER_ERROR = 500,
	NOT_IMPLEMENTED = 501,
	VERSION_NOT_SUPPORTED = 505
};
