#!/bin/bash
echo "Content-Type: text/html"
echo ""
echo "<!DOCTYPE html>"
echo "<html>"
echo "<head>"
echo "<title>Shell CGI Test</title>"
echo "</head>"
echo "<body>"
echo "<h1>Shell CGI Test</h1>"
echo "<p>This is a shell CGI script running on our webserver!</p>"
echo "<p>Current time: $(date)</p>"
echo "<p>Current user: $(whoami)</p>"
echo "<p>Current directory: $(pwd)</p>"
echo "<h2>Environment Variables:</h2>"
echo "<ul>"
for var in $(env | sort); do
    echo "<li><strong>$(echo $var | cut -d'=' -f1):</strong> $(echo $var | cut -d'=' -f2-)</li>"
done
echo "</ul>"
echo "<br>"
echo "<a href='/'>Back to Home</a>"
echo "</body>"
echo "</html>" 